### PR TITLE
Setup eslint

### PR DESCRIPTION
**Pull request by Ovifer13**
**Issue #61**
- [x] Install packages for Eslint to work with TypeScript
- [x] Configure eslintrc file
- [x] Configure tsconfig.js file

### CODE REVIEW

**Comment by Ovifer13** [comment]
https://github.com/typescript-eslint/typescript-eslint

**Comment by Ovifer13** [comment]
https://nextjs.org/docs/basic-features/eslint

**Comment by Ovifer13** [comment]
@sofiaromorales Should I set up [Prettier](https://prettier.io/) too?

**Comment by sofiaromorales** [comment]
@Ovifer13 can you provide an implementation proof or steps on how to test this?

**Pull request merged**
