### PR TITLE
Add View Pricing button on the service detail page that links to Service Packages

### PR DESCRIPTION
**Pull request by Ovifer13**
**Issue #208**

### CODE REVIEW

**Comment by Ovifer13** [comment]
**Proof**
image

**Comment by sofiaromorales** [comment]
@Ovifer13 any reason why you removed the `CAN_YOU_PROVIDE_THESE_SERVICES` button? https://www.figma.com/file/KlLr27PTO7Dzz3D9CE2LzT/setlife-core?node-id=1430%3A12909

**Comment by Ovifer13** [comment]
@sofiaromorales I thought the change was to change that button to view pricing or are we going to have both buttons?

**Comment by Ovifer13** [comment]
@sofiaromorales Doneeee I restored the button, sorry for the confusion

**Comment by sofiaromorales** [comment]
> @sofiaromorales I thought the change was to change that button to view pricing or are we going to have both buttons?

I think we will keep both

**Review by sofiaromorales — APPROVED** [review]

**Pull request merged**
