### PR TITLE
Add Testimonials section

### PR DESCRIPTION
**Pull request by vdegandesa**
New component file and new section on Home page

Title is implemented as a new string

### CODE REVIEW

**Comment by vdegandesa** [comment]
The icon from Figma file was hardcoded inside TestimoniaslTile for reference only (copied from tailwinds icons)

**Comment by vdegandesa** [comment]
Screen Shot 2022-11-08 at 3 24 35 PM

**Comment by vdegandesa** [comment]
@Sofia @ Ovidio I need some help with the styling 
Screen Shot 2022-11-10 at 2 26 56 PM

**Comment by vdegandesa** [comment]
Screen Shot 2022-11-10 at 6 05 54 PM

**Review by sofiaromorales — APPROVED** [review]

**Pull request merged**
