### PR TITLE
Foundation

### PR DESCRIPTION
**Pull request by sofiaromorales**

### CODE REVIEW

**Review by otech47 — COMMENTED** [review]
Looking good so far 👍

**Comment by otech47** [comment]
> https://www.npmjs.com/package/micro

Wow this library looks pretty amazing for the minimal functionalities in this release could be great to use

**Comment by sofiaromorales** [comment]
https://www.npmjs.com/package/apollo-server-micro

**Comment by sofiaromorales** [comment]
https://www.apollographql.com/blog/apollo-client/next-js/next-js-getting-started/

**Review by Ovifer13 — APPROVED** [review]

**Pull request merged**
